# Generated by Django 6.0.7 on 2026-08-05 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0002_alter_borrowing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
